export const userConst = {
    GET_ACCESS_TOKEN: "GET_ACCESS_TOKEN",
    DELETE_ACCESS_TOKEN: "DELETE_ACCESS_TOKEN",
    GET_USER: "GET_USER",
    GET_USER_PLAYLIST: "GET_USER_PLAYLIST",
    GET_USER_RECENTLY_PLAYED: "GET_USER_RECENTLY_PLAYED",
    SEARCH: "SEARCH",
    GET_USER_TOPS: "GET_USER_TOPS"
};

export const spotifyConst = {
    CLIENT_ID: "cc82e43ea4f842d280be69bf9aff76cb",
    REDIRECT_URI: "http://localhost:3000/"
};